### ISSUE TITLE
Prevent Padel Splash Image from Loading

### ISSUE THREAD

**Issue by skolmar** [ECRL/PaDELPy#14]
Hey,

I love this package, it's working great, except for one inconvenience. When I run "from_smiles()" multiple times, such as on a dataframe with thousands of entries, it reloads the Padel splash image each time it does a calculation, making it impossible to work because it's constantly interrupting whatever window I'm using.

I looked at wrapper.py and can see that there is a "_popen_timeout()" function, which has a call to "popen()". I've tried importing "CREATE_NO_WINDOW" from the "subprocess" module and setting "creation_flags = CREATE_NO_WINDOW" in the "popen()" call, but it doesn't fix the problem.

Is there a simple way to prevent the Padel splash image from loading every computation?

Thanks!

**Comment by tjkessler** [comment]
Hi @skolmar,

Thank you for the issue submission, I'm glad you like this package! Unfortunately I do not believe there is a way to suppress the splash screen/image from Python, it is displayed whenever the command line version (or in our specific case, a subprocess call via Python) of PaDEL-Descriptor is executed. From what I can tell, displaying the splash screen is most likely executed from somewhere in PaDEL-Descriptor's source code (PaDEL-Descriptor_src\PaDEL-Descriptor\src\padeldescriptor\PaDELDescriptorApp.java).

I'm going to keep this issue open, I theorize there is a solution (simple or otherwise) and definitely want to implement it into PaDELPy. Perhaps editing PaDEL-Descriptor's source code, suppressing the window from there, and recompiling would fix this 🤔

Best,
Travis
